
name: Terraform Workflow with SonarCloud SAST

on:
  push:
    branches:
      - main
  pull_request:

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  contents: read

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      id: terraform_plan
      run: terraform plan 

  sonarcloud:
    runs-on: ubuntu-latest
    needs: terraform_plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    

    - name: Setup SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=azure-cloud-githubaction-org
          -Dsonar.projectKey=azure-cloud-githubaction-org_new-azure-terraform-ga-sonarcloud-integration
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Check SonarCloud Quality Gate
      id: sonar_quality_gate
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.qualitygate.wait=true
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=azure-cloud-githubaction-org
          -Dsonar.projectKey=azure-cloud-githubaction-org_new-azure-terraform-ga-sonarcloud-integration
      continue-on-error: false
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  terraform:
    runs-on: ubuntu-latest
    needs: sonarcloud

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init


    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && steps.sonar_quality_gate.conclusion == 'success'
      run: terraform apply -auto-approve

